---
title: "Creation of Backuptools"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Creation of Backuptools}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Disclaimer
This document describes the creation process of a set of bash scripts all used for doing different sorts of backups.  


## Dependencies and Requirements
Commonly used bash utility functions are kept in a project/package (still to be created) which should be available for the scripts in this package. 


## Package Architecture
This package uses a central script called `backup_data.sh` for simple backing up of data stored under a common directory somewhere in the directory tree. The content of this directory is compressed into a gzipped-tar-achrive and moved to a specified target directory.


## Specialiced Functionality
More specialised features such as running backups for the gogs-repository or the transfer of backup files to remote backup locations is implemented in their own specific scripts. 


## Cronjob Infrastructure
This section describes the necessary infrastructure to run the backups via a cronjob. The backuptools are installed in a given directory under the users's home directory. Depending on the disk partition architecture, it makes sense to create the backup on a different partition from the source data.


### Backup Jobs
The data to be backedup is specified in backup-job files. These files contain a list of directories to be backedup in a given call to the backup script. In a loop over all directories in all the backup-job files, the data is compressed to gzipped-tar-archives. 


### Cronjob
The cronjob executes a certain run-script which does the loop over all backup-job files. After creating the backups for each directory specified in the backup-jobs, the backup results are moved to a remote backup storage location.


## Deployment
The deployment of the complete set of backuptools is done via `devtools::install_github()`. The deployment process installs the backuptools package as an ordinary R-package under the user-specific R-library directory. From this package, the required components for the desired backup functionality are copied to a specified installation directory. This installation is done via specific installer-scripts called `install_cron_backup.sh`. 




